AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CloudFormation template for S3 bucket

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sample-cicd-bucket-${AWS::Region}-${AWS::AccountId}"

